protected/models/Recarga.php
<?php

Yii::import('application.models._base.BaseRecarga');

class Recarga extends BaseRecarga
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
        
	
	public function cargarUser()
	{
		$session=Yii::app()->getSession();
		$id_user=$session['_id'];
		return ($id_user);
		
	}
	
	public function cargarListasEmpleado(){
		
			$id_user=$this->cargarUser();
			
			$criteria=new CDbCriteria(array(
				'condition'=>'user_id =:user_id and estado =:estado',
				'order'=>'id DESC',
				'limit'=>500,
				'params'=> array(':user_id' => $id_user, ':estado'=>'LISTA'),
					));
			$model=Recarga::model()->findAll($criteria);
			$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
			$dataProvider->setPagination(false);		
			
			return ($dataProvider);

	}
	
	
	public function cargarPendientesEmpleado(){
		
			$id_user=$this->cargarUser();
			
			$criteria=new CDbCriteria(array(
				'condition'=>'user_id =:user_id',
				'order'=>'id DESC',
				'limit'=>500,
				'params'=> array(':user_id' => $id_user),
					));
			$model=Recarga::model()->findAll($criteria);
			$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
			$dataProvider->setPagination(false);		
			
			return ($dataProvider);

	}
	 
	 
	public function cargarPendientesOperador(){
		
			$id_user=$this->cargarUser();
			
			$criteria=new CDbCriteria(array(
				'condition'=>'estado =:estado or estado =:estado2',
				'order'=>'id DESC',
				'limit'=>500,
				'params'=> array(':estado'=>'PENDIENTE', ':estado2'=>'PROCESANDO'),
					));
			$model=Recarga::model()->findAll($criteria);
			$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
			$dataProvider->setPagination(false);		
			
			return ($dataProvider);

	}
	
	public function estaAtendida(){	
	$flag = Atencion::model()->exists('recarga_id =:recarga_id',array(':recarga_id'=>$this->id));
	return $flag;		
	}
	
	public function esMia($user_id){	
	$flag = Atencion::model()->exists('recarga_id =:recarga_id AND user_id = :user_id',array(':recarga_id'=>$this->id,':user_id'=>$user_id));
	return $flag;		
	}

	public function comprobarNoPrepago($celular){	
	$flag = Noprepago::model()->exists('numero =:numero',array(':numero'=>$celular));
	return $flag;		
	}
	
	public function cargarCupo($celular){	
	
	//$flag = Noprepago::model()->exists('numero =:numero and compania =:compania',array(':numero'=>$celular, ':compania'=>$compania));
	$model_cupo = Cupo::model()->findByAttributes(array('numero'=>$celular));
        if(!$model_cupo)
            return new Cupo;
	//$model_cupo = Cupo::model()->findByAttributes( array('numero'=>$numero), 'numero=:numero', array(':numero'=>$celular));
	return $model_cupo;
	
	}

}

protected/controllers/LocalController.php
<?php

class LocalController extends GxController {

	public function filters() {
			return array(
					'rights', 
					);
		}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Local'),
		));
	}

	public function actionCreate() {
		$model = new Local;

		$this->performAjaxValidation($model, 'local-form');

		if (isset($_POST['Local'])) {
			$model->setAttributes($_POST['Local']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Local');

		$this->performAjaxValidation($model, 'local-form');

		if (isset($_POST['Local'])) {
			$model->setAttributes($_POST['Local']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Local')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Local');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Local('search');
		$model->unsetAttributes();

		if (isset($_GET['Local']))
			$model->setAttributes($_GET['Local']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
	
	public function actionVerLocalesCliente() {
		$model = new Local('search');
		$model->unsetAttributes();
		$dataProvider=$model->cargarLocalesCliente();
		
		$this->render('verLocalesCliente',array('dataProvider'=>$dataProvider,'model'=>$model));
	}
	
	public function actionVerLocalCliente($id) {
		
		$model = $this->loadModel($id, 'Local');
		$dataProvider=$model->cargarRecargasLocal($id);
		$this->render('verLocalCliente',array('dataProvider'=>$dataProvider,'model'=>$model));
	}
	
}//finfin

protected/controllers/RecargaController.php
<?php

class RecargaController extends GxController {

	public function filters() {
		return array(
				'rights', 
				);
	}


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Recarga'),
		));
	}

	public function actionCreate(){
		$model = new Recarga;
                $model_cupo=null;

		$this->performAjaxValidation($model, 'recarga-form');
		
		
		if (isset($_POST['Recarga'])) {
			
			$model->setAttributes($_POST['Recarga']);			
			$session=Yii::app()->getSession();
			$model->user_id=$session['_id'];
			$model->local_id=$session['_local'];
                        
			
			/*COMPROBAR RESTRICCIONES*/
			
			$noprepago=$model->comprobarNoPrepago($model->celular);
			
			if(!$noprepago){
				
				/* Aumenta el cupo al realizar una recarga, migrado a AtencionController Action update
				 * if($model->compania=='Entel'){
					$this->actionAumentarCupo($model->celular);				
				}*/
				$model->setAttributes($_POST['Recarga']);			
				$model_cupo=$model->cargarCupo($model->celular);
			
				if($model_cupo->cupo > 0 OR !$model_cupo){
							
					if ($model->save()) {
						if (Yii::app()->getRequest()->getIsAjaxRequest())
							Yii::app()->end();
						else
							$this->redirect(array('verPendientesEmpleado', 'id' => $model->id));
					}
							
				} else
					Yii::app()->user->setFlash('error', 'El celular <strong>'.$model->celular.' </strong>no puede ser recargado.');
			
			} else
				Yii::app()->user->setFlash('info', 'El celular <strong>'.$model->celular.' </strong>no puede ser recargado.');
		}

		$this->render('_crear', array( 'model' => $model, 'cupo'=>$model_cupo));
	}
	
		
	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Recarga');

		$this->performAjaxValidation($model, 'recarga-form');

		if (isset($_POST['Recarga'])) {
			$model->setAttributes($_POST['Recarga']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Recarga')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Recarga');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Recarga('search');
		$model->unsetAttributes();

		if (isset($_GET['Recarga']))
			$model->setAttributes($_GET['Recarga']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

/**********************************************************
			DESCRIP:	MOSTRAR TODAS LAS RECARGAS CON ESTADO PENDIENTE
			REQUIERE:	$ID DEL USUARIO
			UTILIZA:	VISTA 'recargas_pendientes'
************************************************************/	
	public function actionRecargasPendientes() {
		
		$model = new Recarga('search');
		$model->unsetAttributes();

		$criteria=new CDbCriteria(array(
			'condition'=>'estado = :estado',
			'order'=>'id DESC',
			'limit'=>500,
			'params'=> array(':estado' => 'PENDIENTE'),
		));
		
		$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
		$dataProvider->setPagination(false);
		//FIN CONSULTA
		$this->render('recargas_pendientes',array('dataProvider'=>$dataProvider));
		
	}
	
	
/********************
			DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS ATENDIDAS Y APROBADAS POR UN OPERADOR
			REQUIERE:	$ID DEL USUARIO
			UTILIZA:	VISTA 'recargas_atendidas'
********************/	
	public function actionRecargasAtendidas()
{
		$model = new Recarga('search');
		$model->unsetAttributes();
		$criteria=new CDbCriteria(array(
			'condition'=>'usuario_id = :usuario_id',
			'order'=>'id DESC',
			'limit'=>500,
			'params'=> array(':usuario_id' => 1),
		));
		$model=Recarga::model()->findAll($criteria);
		$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
		$dataProvider->setPagination(false);
		
		
		//FIN CONSULTA
		$this->render('recargas_atendidas',array('dataProvider'=>$dataProvider,'model'=>$model));
	}
	
	/********************
			DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS REALIZADAS POR LOS EMPLEADOS DE UN CLIENTE
			REQUIERE:	$ID DEL CLIENTE
			UTILIZA:	VISTA 'recargas_realizadas'
*******************
	public function actionRecargasRealizadas()
	{
			$model = new Recarga('search');
			$model->unsetAttributes();
			$session=Yii::app()->getSession();
			$id_user=($session['_id']);
			
			$criteria=new CDbCriteria(array(
				'condition'=>'user_id =:user_id and estado =:estado',
				'order'=>'id DESC',
				'limit'=>500,
				'params'=> array(':user_id' => $id_user, ':estado'=>'PENDIENTE'),
					));
			$model=Recarga::model()->findAll($criteria);
			$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
			$dataProvider->setPagination(false);		
			
			//FIN CONSULTA
			$this->render('recargas_realizadas',array('dataProvider'=>$dataProvider,'model'=>$model));
		} */
  
/********************
 * 	DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS INGRESADAS POR EL EMPLEADO.
	REQUIERE:	$ID DEL EMPLEADO
	UTILIZA:	VISTA 'Ver_Recargas'
********************/

	public function actionRecargasIngresadas()
	{
			$model = new Recarga('search');
			$model->unsetAttributes();
			
			$criteria=new CDbCriteria(array(
				'condition'=>'usuario_id =:usuario_id',
				'order'=>'id DESC',
				'limit'=>500,
				'params'=> array(':usuario_id' => 1),
					));
			$model=Recarga::model()->findAll($criteria);
			$dataProvider=new CActiveDataProvider('Recarga',array('criteria'=>$criteria,));
			$dataProvider->setPagination(false);
			
			
			//FIN CONSULTA
			$this->render('recargas_ingresadas',array('dataProvider'=>$dataProvider,'model'=>$model));
		}
	
	
	/********************
 * 	DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS INGRESADAS POR EL EMPLEADO).
	REQUIERE:	
	UTILIZA:	MODELO cargarListas, VISTA verListas
********************/
	
	public function actionVerListasEmpleado()
	{
		
		$model = new Recarga('search');
		$model->unsetAttributes();
		$dataProvider=$model->cargarListasEmpleado();
			
		$this->render('verRecargasEmpleado',array('dataProvider'=>$dataProvider,'model'=>$model));
		
	}
	
	
/********************
 	DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS PENDIENTES POR EL EMPLEADO).
	REQUIERE:	
	UTILIZA:	MODELO cargarPendientesEmpleado, VISTA verListas
********************/
	
	public function actionVerPendientesEmpleado()
	{
		$model = new Recarga('search');
		$model->unsetAttributes();
		$dataProvider=$model->cargarPendientesEmpleado();
			
		$this->render('verRecargasEmpleado',array('dataProvider'=>$dataProvider,'model'=>$model));
	}

/********************
 	DESCRIP:	ACTION QUE PERMITE VER TODAS LAS RECARGAS PENDIENTES).
	REQUIERE:	
	UTILIZA:	MODELO cargarPendientesOperador, VISTA verListas
********************/
	
	public function actionVerPendientesOperador()
	{
		$model = new Recarga('search');
		$model->unsetAttributes();
		$dataProvider=$model->cargarPendientesOperador();
			
		$this->render('recargasPendientesOperador',array('dataProvider'=>$dataProvider,'model'=>$model));
	}

/********************
 	DESCRIP:	ACTION QUE PERMITE VER LAS RECARGAS RECHAZADAS POR EL EMPLEADO).
	REQUIERE:	
	UTILIZA:	MODELO cargarPendientes, VISTA verListas
********************/

	public function actionExport (){
			
		$model = new User('search');
		$model->unsetAttributes();
		//$model=$model->cargarUser();
		$id_user=User::model()->cargarUser();
		
		$model = $this->loadModel($id_user, 'User');
		
		Yii::app()->request->sendFile('recargas_'.$model->username.'.xls', 		
			$this->renderPartial('excel', array(
			'model' => $model,
			),true) 
		);

	}

	
}

protected/views/recarga/_crear.php
<script type="text/javaScript">
function confirmarDatos(){

 $("#numero_celular").text($("#Recarga_celular").val());
 $("#numero_monto").text($(".compactRadioGroup [name=Recarga[monto]]:radio:checked").val());

}

function init(){
$("#Recarga_compania_0").attr("checked",true);
$("#Recarga_monto_0").attr("checked",true);

	$("#Recarga_celular").keypress(function (e){
		var keycode=e.which;
		if(48>keycode || keycode>57){
		if(keycode!=8){
		return false;
		}
		}
		});

$("#Recarga_compania_0").click(function() {

  $("#Recarga_monto_0").val("500");
  $(".compactRadioGroup label:eq(0)").text("");
  $(".compactRadioGroup label:eq(0)").text("500");  
  
  $("#Recarga_monto_1").val("1000");
  $(".compactRadioGroup label:eq(1)").text("");
  $(".compactRadioGroup label:eq(1)").text("1000");
  
  $("#Recarga_monto_2").val("1500");
  $(".compactRadioGroup label:eq(2)").text("");
  $(".compactRadioGroup label:eq(2)").text("1500");
  
  $("#numero_compania").text("MOVISTAR");
       
});
$("#Recarga_compania_1").click(function() {
  $("#Recarga_monto_0").val("1000");
  $(".compactRadioGroup label:eq(0)").text("");
  $(".compactRadioGroup label:eq(0)").text("1000");
  
  $("#Recarga_monto_1").val("2000");
  $(".compactRadioGroup label:eq(1)").text("");
  $(".compactRadioGroup label:eq(1)").text("2000");
  
  $("#Recarga_monto_2").val("3000");
  $(".compactRadioGroup label:eq(2)").text("");
  $(".compactRadioGroup label:eq(2)").text("3000");
  
  $("#numero_compania").text("ENTEL");
     
});

$('#recarga-form').submit(function(){
if($("#Recarga_celular").val().length!=8){
  alert("EL CELULAR DEBE SER DE 8 DIGITOS");
  return false;
  }
  }
);
}
$(document).ready(init);

</script>

<?php
if(Yii::app()->user->hasFlash('error')){?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('error'); ?>
</div>

<?php }?>

<?php
if(Yii::app()->user->hasFlash('info')){?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('info'); ?>
</div>

<?php }?>	
	
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'recarga-form',
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'celular',array('style'=>'font-size:25px')); ?>
		<?php echo $form->textField($model,'celular',array('size'=>8,'maxlength'=>8)); ?>
		<?php echo $form->error($model,'celular'); ?>
	</div>

	<div class="row">
	<div class="hola">
		<?php echo $form->radioButtonList($model,'compania',array('Movistar' => 'Movistar', 'Entel' => 'Entel'),array('labelOptions'=>array('style'=>'display:inline'))); ?>
	</div>
		<?php echo $form->error($model,'compania'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'monto',array('style'=>'font-size:25px')); ?>
	<div class="compactRadioGroup">
		<?php echo $form->radioButtonList($model,'monto',array('500' => '500', '1000' => '1000', '1500' => '1500'),array('labelOptions'=>array('style'=>'display:inline'))); ?>
	</div>
		<?php echo $form->error($model,'monto'); ?>
	</div>
   
	
	<div class="row buttons">
				<?php //$this->widget('bootstrap.widgets.BootButton', array('buttonType'=>'reset', 'type'=>'primary', 'icon'=>'ok white', 'label'=>'INGRESAR')); ?> 
				<?php $this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'INGRESAR',
	'url'=>'#myModal',
    'type'=>'primary',
	'htmlOptions'=>array(
			'data-toggle'=>'modal',
			'onclick'=>'js: confirmarDatos();
						 $("button[name=yt0]").focus();	',
			),
   )); ?>
	</div>


<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'myModal')); ?>
 
<div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3>CONFIRMACION DE RECARGA</h3>
</div>
 
<div class="modal-body">
    <strong>NUMERO:</strong> <span id="numero_celular">855566689</span><br>
	<strong>MONTO:</strong> <span id="numero_monto">855566689</span><br>
	<strong>COMPANIA:</strong> <span id="numero_compania">MOVISTAR</span><br>
</div>
 
<div class="modal-footer">
  <?php $this->widget('bootstrap.widgets.TbButton', array(
        'type'=>'success',
		'icon'=>'ok white',
		'buttonType'=>'submit', 
        'label'=>'CONFIRMAR',
        'htmlOptions'=>array(
			'data-dismiss'=>'modal',
			'onclick'=>'js: $("#recarga-form").submit();',
			),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'label'=>'CANCELAR',
		'icon'=>'remove white',
		'buttonType'=>'reset', 
		'type'=>'danger',
		'htmlOptions'=>array(
			'data-dismiss'=>'modal',
			//'onclick'=>'js: alert("CANCELAR");',
			),
    )); ?>
	
</div>
 

  
	<?php $this->endWidget(); ?>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/recarga/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'recarga-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'user_id'); ?>
		<?php echo $form->dropDownList($model, 'user_id', GxHtml::listDataEx(User::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'user_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'local_id'); ?>
		<?php echo $form->dropDownList($model, 'local_id', GxHtml::listDataEx(Local::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'local_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'celular'); ?>
		<?php echo $form->textField($model, 'celular', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'celular'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'compania'); ?>
		<?php echo $form->textField($model, 'compania', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'compania'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'monto'); ?>
		<?php echo $form->textField($model, 'monto', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'monto'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'comentario'); ?>
		<?php echo $form->textField($model, 'comentario', array('maxlength' => 200)); ?>
		<?php echo $form->error($model,'comentario'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'estado'); ?>
		<?php echo $form->textField($model, 'estado', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'estado'); ?>
		</div><!-- row -->

		<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/recarga/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('user_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->user)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('local_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->local)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('celular')); ?>:
	<?php echo GxHtml::encode($data->celular); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('compania')); ?>:
	<?php echo GxHtml::encode($data->compania); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('monto')); ?>:
	<?php echo GxHtml::encode($data->monto); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('comentario')); ?>:
	<?php echo GxHtml::encode($data->comentario); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('estado')); ?>:
	<?php echo GxHtml::encode($data->estado); ?>
	<br />
	*/ ?>

</div>

protected/views/recarga/recargas_pendientes_alvaro.php
<script type="text/javaScript">
function init(){

grill.update('recargas_pendientes-grid');
setTimeout("init()", 5000)
}
$(document).ready(function(){
grilla = $.fn.yiiGridView.update('recargas_pendientes-grid');
init();
});
</script>

<?php
$this->breadcrumbs=array(
	'Recargas',
);

$this->menu=array(
	array('label'=>'Crear Recarga', 'url'=>array('create')),
	array('label'=>'Ver Ultimas recargas', 'url'=>array('ultimas')),
	array('label'=>'Ver mis Recarga', 'url'=>array('mias')),
);

?>
<h1>Recargas</h1>


<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'recargas_pendientes-grid',
	'dataProvider'=>$dataProvider,
	'type'=>'striped bordered condensed',
	//'filter' => $model,
	'template'=>"{items}",
	'columns' => array(
		array(
            'name'=>'OTE',
            'value'=>'$data->id',
        ),
		array(
            'name'=>'Compania',
            'value'=>'$data->compania',
        ),
		'celular',
		'monto',
		'estado',


	array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view}{atender}',
			'buttons'=>array
			(			
			'view' => array('label' => 'Ver Recarga','url'=>'Yii::app()->createUrl("recarga/view", array("id"=>$data->id))',),
			'atender' => array(
					'label'=>'Atender',
					'url'=>'Yii::app()->createUrl("atencion/creaatencion", array("id"=>$data->id))',
					'icon'=>'check',
					'options' => array(
						'onclick'=>"js:$('#dialog_recarga').dialog('open')",
						'ajax'=>array(
							'url'=>"js:$(this).attr('href')",
							'data'=> "js:$(this).serialize()",
							'type'=>'post',
							'dataType'=>'json',
							'success'=>"function(data){
										$('#dialog_recarga').html(data.mensaje);
							}",
							),
						),
				),				
				),
			),	
	
	
)
        ))
        ;
?>


<?php
$this->beginWidget('zii.widgets.jui.CJuiDialog', array( 
    'id'=>'dialog_recarga',
    'options'=>array(
        'title'=>'Crear atencion',
        'autoOpen'=>false,
        'modal'=>true,
        'width'=>550,
        'height'=>470,
    ),
));?>
<div id="dialog_recarga"></div>
 
<?php $this->endWidget();?>

protected/views/recarga/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
array(
			'name' => 'local',
			'type' => 'raw',
			'value' => $model->local !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->local)), array('local/view', 'id' => GxActiveRecord::extractPkValue($model->local, true))) : null,
			),
'celular',
'compania',
'monto',
'estado',
	),
)); ?>